# Generated by Django 3.2.7 on 2022-10-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_date_buyer_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, null=True)),
                ('Name', models.CharField(max_length=120, null=True)),
                ('LastName', models.CharField(max_length=120, null=True)),
                ('city', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='seller',
            name='date',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(auto_now=True),
        ),
    ]
