# Generated by Django 3.2.7 on 2022-10-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_buyer_purchase_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producat',
            new_name='product',
        ),
    ]
