# Generated by Django 3.2.7 on 2022-10-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_producat_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(default=' Indore', max_length=150),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(default='Piyush Pawar', max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(default='+91 9131721743'),
        ),
    ]
